package yagura.view;

import aspx.viewstate.ViewState;
import aspx.viewstate.ViewStateParser;
import burp.BurpExtender;
import burp.IMessageEditorController;
import burp.IMessageEditorTab;
import burp.IMessageEditorTabFactory;
import burp.IParameter;
import burp.IRequestInfo;
import extend.util.ConvertUtil;
import extend.util.SwingUtil;
import extend.util.external.JsonUtil;
import java.awt.Component;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.SwingWorker;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author isayan
 */
public class ViewStateTab extends javax.swing.JPanel implements IMessageEditorTabFactory, IMessageEditorTab {

    private IMessageEditorController controller = null;
    
    /**
     * Creates new form ViewStateTab
     */
    public ViewStateTab() {
        initComponents();
        customizeComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTree = new javax.swing.JPanel();
        scrollTree = new javax.swing.JScrollPane();
        treeJSON = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        btnExpand = new javax.swing.JButton();
        btnCollapse = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlTree.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeJSON.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        scrollTree.setViewportView(treeJSON);

        pnlTree.add(scrollTree, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnExpand.setText("expand");
        btnExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpandActionPerformed(evt);
            }
        });
        jPanel1.add(btnExpand);

        btnCollapse.setText("collapse");
        btnCollapse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollapseActionPerformed(evt);
            }
        });
        jPanel1.add(btnCollapse);

        pnlTree.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        add(pnlTree, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTreeModel modelJSON;
    
    @SuppressWarnings("unchecked")
    private void customizeComponents() {
        Icon emptyIcon = SwingUtil.createEmptyIcon();
        DefaultTreeCellRenderer renderer = (DefaultTreeCellRenderer) this.treeJSON.getCellRenderer();
        renderer.setOpenIcon(emptyIcon);
        renderer.setClosedIcon(emptyIcon);
        renderer.setLeafIcon(emptyIcon);
        this.modelJSON = (DefaultTreeModel) this.treeJSON.getModel();
        this.clearViewState();
    }
    
    private void btnExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpandActionPerformed
        expandJsonTree();
    }//GEN-LAST:event_btnExpandActionPerformed

    private void btnCollapseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollapseActionPerformed
        collapseJsonTree();
    }//GEN-LAST:event_btnCollapseActionPerformed

    @Override
    public IMessageEditorTab createNewInstance(IMessageEditorController controller, boolean editable) {
        this.controller = controller;
        return this;
    }

    @Override
    public String getTabCaption() {
        return "ViewState";
    }

    @Override
    public Component getUiComponent() {
        return this;
    }

    @Override
    public boolean isEnabled(byte[] content, boolean isMessageRequest) {
        if (!isMessageRequest) {
            return false;
        }        
        if (content == null || content.length == 0) {
            return false;
        }
        IRequestInfo reqInfo = BurpExtender.getHelpers().analyzeRequest(content);
        List<IParameter> parameters = reqInfo.getParameters();
        for (IParameter p : parameters) {
            if (p.getType() == IParameter.PARAM_BODY) {
                if ("__VIEWSTATE".equals(p.getName()) && !"".equals(p.getValue())) {                  
                    return true;
                }
            }
        }        
        return false;
    }

    private byte [] message = null;
    
    @Override
    public void setMessage(byte[] content, boolean isMessageRequest) {
        this.message = content;
        if (content != null) {
            String viewStateValue = null;
            IRequestInfo reqInfo = BurpExtender.getHelpers().analyzeRequest(content);
            List<IParameter> parameters = reqInfo.getParameters();
            for (IParameter p : parameters) {
                if (p.getType() == IParameter.PARAM_BODY) {
                    if ("__VIEWSTATE".equals(p.getName()) && !"".equals(p.getValue())) {
                        viewStateValue = p.getValue();
                        break;
                    }
                }
            }        
            setViewState(viewStateValue);
        }
    }

    @Override
    public byte[] getMessage() {
        if (this.message != null) {
            return this.message;
        } else {
            return new byte[]{};
        }
    }

    public void setViewState(String viewStateValue) {
        if (viewStateValue == null) {
            return ;
        }
        if (ViewStateParser.isUrlencoded(viewStateValue)) {
            viewStateValue = URLDecoder.decode(viewStateValue, StandardCharsets.ISO_8859_1);
        }
        final ViewStateParser vs = new ViewStateParser();
        final String viewStateDecode = viewStateValue;
        try {
            // Tree View
            SwingWorker swTree = new SwingWorker<DefaultTreeModel, Object>() {
                @Override
                protected DefaultTreeModel doInBackground() throws Exception {
                    publish("...");
                    final ViewState viewState = vs.parse(viewStateDecode);
                    publish("...", "...");
                    if (viewState.isEncrypted()) {
                        return JsonUtil.toJsonTreeModel(ViewState.ENCRYPTED_JSON, "viewState");
                    }
                    else {
                        String enabled = viewState.isMacEnabled() ? "[MAC enabled]" :  "[MAC disnabled]";
                        return (DefaultTreeModel)JsonUtil.toJsonTreeModel(viewState.toJson(), "viewState" + " - " + enabled);
                    }
                }

                protected void process(List<Object> chunks) {
                    modelJSON.setRoot(new DefaultMutableTreeNode("Heavy Processing" + ConvertUtil.repeat("...", chunks.size())));
                }

                protected void done() {
                    try {
                        modelJSON = get();
                        SwingUtil.allNodesChanged(treeJSON);
                        treeJSON.setModel(modelJSON);
                        expandJsonTree();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ViewStateTab.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ExecutionException ex) {
                        Logger.getLogger(ViewStateTab.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            swTree.execute();
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(ViewStateTab.class.getName()).log(Level.WARNING, null, ex);
        }
    }

    public void clearViewState() {
        this.treeJSON.setModel(JsonUtil.toTreeNodeModel("viewState"));
    }

    @Override
    public boolean isModified() {
        return false;
    }

    @Override
    public byte[] getSelectedData() {
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollapse;
    private javax.swing.JButton btnExpand;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlTree;
    private javax.swing.JScrollPane scrollTree;
    private javax.swing.JTree treeJSON;
    // End of variables declaration//GEN-END:variables

    public void expandJsonTree() {
        TreePath path = this.treeJSON.getSelectionPath();
        if (path == null) {
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) this.modelJSON.getRoot();
            path = new TreePath(root.getPath());
        }
        SwingUtil.expandAll(this.treeJSON, path);
    }

    public void collapseJsonTree() {
        TreePath path = this.treeJSON.getSelectionPath();
        if (path == null) {
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) this.modelJSON.getRoot();
            path = new TreePath(root.getPath());
        }
        SwingUtil.collapseAll(this.treeJSON, path);
    }

}
